apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - "../../base"

images:
  - name: stonesoup-pr-ratelimiter-controller
    newName: pipelinerun-rate-limiter-image
    newTag: dev
