apiVersion: v1
kind: Service
metadata:
  labels:
    app: stonesoup-pr-ratelimiter-controller
  name: stonesoup-pr-ratelimiter-controller-monitor
  namespace: pipelinerun-rate-limiter
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - name: http-metrics
      port: 8080
      protocol: TCP
      targetPort: 8080
    - name: probes
      port: 8081
      protocol: TCP
      targetPort: 8081
  selector:
    app: stonesoup-pr-ratelimiter-controller
  sessionAffinity: None
  type: ClusterIP
