apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: stonesoup-pr-ratelimiter-controller
  labels:
    rbac.authorization.k8s.io/aggregate-to-edit: "true"
rules:
  - apiGroups:
      - quota.openshift.io
    resources:
      - clusterresourcequotas
    verbs:
      - get
      - list
      - watch

  - apiGroups:
    - apiextensions.k8s.io
    resources:
    - customresourcedefinitions
    verbs:
    - get

  - apiGroups:
      - tekton.dev
    resources:
      - pipelineruns
      - pipelineruns/status
    verbs:
      - create
      - delete
      - deletecollection
      - get
      - list
      - patch
      - update
      - watch

  - apiGroups:
      - metrics.k8s.io
    resources:
      - podnodemetrics
      - pods
      - nodemetrics
      - nodes
    verbs:
      - get
      - list
      - watch

  - apiGroups:
      - ''
      - events.k8s.io
    resources:
      - events
    verbs:
      - create
      - patch
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - get
      - list
      - watch
      - delete
  - apiGroups:
      - ""
    resources:
      - resourcequotas
      - nodes
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: stonesoup-pr-ratelimiter-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: stonesoup-pr-ratelimiter-controller
subjects:
  - kind: ServiceAccount
    name: stonesoup-pr-ratelimiter-controller
    namespace: pipelinerun-rate-limiter
